### PR TITLE
Wrap driver

### PR DESCRIPTION
**Pull request by aprobus**
## Problem

Mesomatic provides wrapping of the scheduler and driver, but the scheduler still receives a raw mesos driver instead of the wrapped driver.
## Solution

The `wrap-scheduler` function will now wrap the driver when delegating to the clojure scheduler.

### CODE REVIEW

**Comment by pyr** [comment]
Thanks for this aaron!

**Comment by aprobus** [comment]
Thanks for merging so quickly! Would you be able to put the new version up on clojars?

**Comment by aprobus** [comment]
@pyr Sorry for bugging you, but would you be able to put the new version up on clojars?

**Comment by pyr** [comment]
I'll get on it tomorrow, away today, sorry!

Aaron Probus writes:

**Comment by pyr** [comment]
@aprobus it's deployed, sorry for the wait.

**Comment by aprobus** [comment]
:+1: Thanks @pyr!

**Pull request merged**
