### PR TITLE
types: Add missing label and DiscoveryInfo fields to TaskInfo.

### PR DESCRIPTION
**Pull request by mforsyth**
Also added necessary support for ->pb for :Labels and :Label.

### CODE REVIEW

**Comment by shoe** [comment]
@mforsyth which version of the Mesos API does this support?

**Comment by mforsyth** [comment]
0.28.0 (The version of Mesomatic shadows the version of Mesos API).  Labels for TaskInfo were added in Mesos API 0.22.0.

**Comment by wyegelwel** [comment]
Is there anything preventing this from being merged? We are hoping to use mesosmatic with labels in Cook.

**Comment by pyr** [comment]
@wyegelwel sorry for taking so long!

**Comment by wyegelwel** [comment]
No worries @pyr, thanks for merging it! How often do you bump the version and push a new jar to clojars? We are looking forward to making the switch to mesomatic!

**Comment by pyr** [comment]
I want to look into bumping to latest mesos and would cut a follow-up release, does that fit with your goals?

**Comment by wyegelwel** [comment]
@pyr  as in bump to Mesos 1.0?

**Comment by wyegelwel** [comment]
Hey @pyr, I don't want to rush you on this, so we will push the current jar into clojar as our account and switch back to your version once you push the next version. Thanks again for all your help, we are excited to be using Mesomatic!

**Comment by pyr** [comment]
@wyegelwel the release is out, sorry for the wait

**Pull request merged**
